import type { BuildCaseId } from './build-case-stages'

// Editable mockup copy. Values initially match the existing rendered websites.
export const BUILD_CASE_COPY: Record<BuildCaseId, Record<'before' | 'after', Record<string, string>>> = {
  "summit-hvac": {
    "before": {
      "BCCU Temp": "BCCU Temp",
      "Home · Services · About · Contact": "Home · Services · About · Contact",
      "CALL NOW FOR A FREE ESTIMATE — (540) 555-0199": "CALL NOW FOR A FREE ESTIMATE — (540) 555-0199",
      "Welcome to Our Website!": "Welcome to Our Website!",
      "We have been your local HVAC experts since 2011. Air conditioning, furnaces, heat pumps, and maintenance plans for Staunton and Augusta County.": "We have been your local HVAC experts since 2011. Air conditioning, furnaces, heat pumps, and maintenance plans for Staunton and Augusta County.",
      "Request a Quote": "Request a Quote",
      "Service": "Service",
      "Click": "Click",
      "AC Repair": "AC Repair",
      "Furnace Tune-Up": "Furnace Tune-Up",
      "Heat Pumps": "Heat Pumps",
      "Duct Cleaning": "Duct Cleaning",
      "More info": "More info",
      "© 2015 BCCU Temp · Best viewed in Internet Explorer": "© 2015 BCCU Temp · Best viewed in Internet Explorer"
    },
    "after": {
      "184": "184",
      "BCCU": "BCCU",
      " Temp": " Temp",
      "Services": "Services",
      "Rebates": "Rebates",
      "(540) 555-0199": "(540) 555-0199",
      "Staunton & Augusta County": "Staunton & Augusta County",
      "Fast heat & air repairs in your driveway today.": "Fast heat & air repairs in your driveway today.",
      "4.9 Stars · 184 Google Reviews": "4.9 Stars · 184 Google Reviews",
      "Request Service": "Request Service",
      "View Seasonal Rebates": "View Seasonal Rebates",
      "Same-day dispatch": "Same-day dispatch",
      "NATE techs for AC, furnaces, and heat pumps. Financing on qualifying installs.": "NATE techs for AC, furnaces, and heat pumps. Financing on qualifying installs.",
      "Emergency": "Emergency",
      "24/7 line": "24/7 line",
      "Maintenance": "Maintenance",
      "Priority slots": "Priority slots",
      "Installs": "Installs",
      "Rebate help": "Rebate help",
      "Area": "Area",
      "Valley-wide": "Valley-wide",
      "14yr": "14yr",
      "Local crew": "Local crew",
      "Reviews": "Reviews",
      "Same": "Same",
      "Day slots": "Day slots",
      "NATE": "NATE",
      "Certified": "Certified"
    }
  },
  "northline-dental": {
    "before": {
      "Procedures": "Procedures",
      "Cleanings": "Cleanings",
      "Fillings": "Fillings",
      "Crowns": "Crowns",
      "Bridges": "Bridges",
      "Root Canal": "Root Canal",
      "Whitening": "Whitening",
      "Implants": "Implants",
      "Dentures": "Dentures",
      "Invisalign": "Invisalign",
      "Veneers": "Veneers",
      "Sealants": "Sealants",
      "Extractions": "Extractions",
      "Night Guards": "Night Guards",
      "TMJ": "TMJ",
      "Pediatrics": "Pediatrics",
      "Emergencies": "Emergencies",
      "X-Rays": "X-Rays",
      "Consults": "Consults",
      "Insurance": "Insurance",
      "Forms": "Forms",
      "Augusta Dental Arts": "Augusta Dental Arts",
      "Request an appointment (12 fields)": "Request an appointment (12 fields)",
      "Submit Form": "Submit Form",
      "Office hours Mon–Fri. Call for emergencies. Powered by GenericDentistTheme.": "Office hours Mon–Fri. Call for emergencies. Powered by GenericDentistTheme."
    },
    "after": {
      "AUGUSTA DENTAL ARTS": "AUGUSTA DENTAL ARTS",
      "Book Consultation": "Book Consultation",
      "Modern cosmetic care.": "Modern cosmetic care.",
      "Confident smiles.": "Confident smiles.",
      "Invisalign Preferred Provider": "Invisalign Preferred Provider",
      "Delta Dental / MetLife accepted": "Delta Dental / MetLife accepted",
      "Smile gallery · before / after transformations": "Smile gallery · before / after transformations",
      "Cleanings": "Cleanings",
      "Gentle exams that stay on schedule": "Gentle exams that stay on schedule",
      "Whitening": "Whitening",
      "In-office and take-home options": "In-office and take-home options",
      "Implants": "Implants",
      "Restorative plans with clear pricing": "Restorative plans with clear pricing",
      "New patients welcome · Staunton · Mon–Fri 8–5": "New patients welcome · Staunton · Mon–Fri 8–5",
      "Reserve a chair": "Reserve a chair"
    }
  },
  "ridge-plumbing": {
    "before": {
      "West & Clay": "West & Clay",
      "Custom Carpentry · Additions · Decks · Since forever": "Custom Carpentry · Additions · Decks · Since forever",
      "We do custom carpentry additions decks kitchens and more for homes around town. Our team has years of experience building things the right way. Please email us for information about your project. We can send pictures of past jobs if you ask. Pricing varies depending on materials and scope. Contact info@westandclay.example for a quote whenever you are ready.": "We do custom carpentry additions decks kitchens and more for homes around town. Our team has years of experience building things the right way. Please email us for information about your project. We can send pictures of past jobs if you ask. Pricing varies depending on materials and scope. Contact info@westandclay.example for a quote whenever you are ready.",
      "blurry jobsite.png": "blurry jobsite.png",
      "email us for pricing": "email us for pricing",
      "No forms. No gallery. Just a wall of text like it is 2009.": "No forms. No gallery. Just a wall of text like it is 2009.",
      "Copyright West & Clay · Site by Canva Website Builder": "Copyright West & Clay · Site by Canva Website Builder"
    },
    "after": {
      "18": "18",
      "Custom carpentry": "Custom carpentry",
      "West & Clay": "West & Clay",
      "Lookbook": "Lookbook",
      "Pricing Guide": "Pricing Guide",
      "Built for generations.": "Built for generations.",
      "Custom additions, millwork, and remodels with upfront pricing.": "Custom additions, millwork, and remodels with upfront pricing.",
      "Schedule Design Intake": "Schedule Design Intake",
      "Download 2026 Guide": "Download 2026 Guide",
      "Additions": "Additions",
      "Millwork": "Millwork",
      "2.8x": "2.8x",
      "Qualified leads": "Qualified leads",
      "Active builds": "Active builds",
      "100%": "100%",
      "Written estimates": "Written estimates",
      "VA": "VA",
      "Licensed": "Licensed"
    }
  }
}
