export const siteContent = {
  statusBadge: 'Available for projects',
  founderLine: 'Zachary Maximus',
  brandLine: 'Maximus Reach',
  heroLine1: "Let's build",
  heroLine2: 'something great',
  heroSubtext: 'Digital Growth · Web Development · Ad Management',
  ctaPrimary: 'Get in touch',
  ctaSecondary: 'View work',
  ctaPrimaryHref: '#contact',
  ctaSecondaryHref: '#work',
  navCta: 'Contact',
  navCtaHref: '#contact',
  nav: [
    { label: 'Work', href: '#work' },
    { label: 'About', href: '/about' },
    { label: 'Contact', href: '#contact' },
  ],
  deviceZoom: {
    headline: 'The clearest view of your digital growth',
    subline: 'Websites, ads, and local presence in one place.',
    tabs: [
      { id: 'growth', label: 'Growth' },
      { id: 'web', label: 'Web' },
      { id: 'ads', label: 'Ads' },
      { id: 'creative', label: 'Creative' },
    ],
    panels: {
      growth: {
        title: 'Local visibility',
        stat: '+142%',
        label: 'Profile views',
        detail: 'Google listing optimization across Staunton and surrounding markets.',
      },
      web: {
        title: 'Site performance',
        stat: '98',
        label: 'Speed score',
        detail: 'Fast, polished sites built to convert visitors into leads.',
      },
      ads: {
        title: 'Ad performance',
        stat: '4.2x',
        label: 'Return on spend',
        detail: 'Campaigns tuned weekly so budget goes toward real results.',
      },
      creative: {
        title: 'Content output',
        stat: '24',
        label: 'Assets delivered',
        detail: 'Video, graphics, and copy that match your brand voice.',
      },
    },
  },
  contact: {
    label: 'Get in touch',
    headline: "Let's build",
    headlineEm: 'something great',
    email: 'hello@maximusreach.com',
    phone: '(540) 416-2983',
    tagline: 'Digital Growth · Web Development · Ad Management',
  },
  work: {
    label: 'Selected work',
    headline: 'Sample projects',
    headlineEm: 'you can review',
    sub: 'Concepts and campaigns for websites, ads, and overall growth.',
    viewAll: 'View full portfolio',
    viewAllHref: '/portfolio',
    items: [
      {
        title: 'Gym Website Redesign',
        category: 'Web Development',
        badge: 'Concept Project',
        href: '/portfolio#fitness-landing',
      },
      {
        title: 'Med Spa Facebook Ads',
        category: 'Ad Management',
        badge: 'Sample Campaign',
        href: '/portfolio#medspa-ads',
      },
      {
        title: 'Restaurant Google Listing',
        category: 'Digital Growth',
        badge: 'Concept Project',
        href: '/portfolio#restaurant-growth',
      },
    ],
  },
}
